tinyMCE.addI18n('es.table_dlg',{
general_tab:"General",
advanced_tab:"Avanzada",
general_props:"Propiedades generales",
advanced_props:"Propiedades avanzadas",
rowtype:"Fila en la tabla parte",
title:"Insertar/Modificar tabla",
width:"Ancho",
height:"Alto",
cols:"Columnas",
rows:"Filas",
cellspacing:"Cellspacing",
cellpadding:"Cellpadding",
border:"Borde",
align:"Alineación",
align_default:"Defecto",
align_left:"Izquierda",
align_right:"Derecha",
align_middle:"Centro",
row_title:"Propiedades de fila de la tabla",
cell_title:"Propiedades de columna de la tabla",
cell_type:"Tipo de celda",
valign:"Alineación Vertical",
align_top:"Top",
align_bottom:"Bottom",
bordercolor:"Color del borde",
bgcolor:"Color de fondo",
merge_cells_title:"Merge table cells",
id:"Id",
style:"Estilo",
langdir:"Dirección lenguaje",
langcode:"Codigo lenguaje",
mime:"Target MIME type",
ltr:"De izquierda a derecha",
rtl:"De derecha a izquierda",
bgimage:"Imagen de fondo",
summary:"Resumen",
td:"Datos",
th:"Encabezado",
cell_cell:"Actualización de la celda actual",
cell_row:"Actualizar todas las celdas de la fila",
cell_all:"Actualizar todas las celdas de tabla",
row_row:"Actualización de la fila actual",
row_odd:"Actualizar las filas impares en el cuadro",
row_even:"Actualización de filas, incluso en el cuadro",
row_all:"Actualización de todas las filas en la tabla",
thead:"Table Head",
tbody:"Table Body",
tfoot:"Table Foot",
scope:"Scope",
rowgroup:"Row Group",
colgroup:"Col Group",
col_limit:"You've exceeded the maximum number of columns of {$cols}.",
row_limit:"You've exceeded the maximum number of rows of {$rows}.",
cell_limit:"You've exceeded the maximum number of cells of {$cells}.",
missing_scope:"Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.",
caption:"Table caption",
frame:"Frame",
frame_none:"none",
frame_groups:"groups",
frame_rows:"rows",
frame_cols:"cols",
frame_all:"all",
rules:"Rules",
rules_void:"void",
rules_above:"above",
rules_below:"below",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"box",
rules_border:"border"
});